### ISSUE TITLE
400 Invalid Signature

### ISSUE THREAD

**Issue by matthewtrask** [stevenmaguire/yelp-php#17]
Hey, picked up this error when doing some testing. Regenerated my creds and still get the 400 INVALID SIGNATURE on the request. 

```
Client error: `GET http://api.yelp.com/v2/search/?term=tacos&location=Nashville%2C+TN&limit=10` resulted in a `400 Bad Request` response:
{"error": {"text": "Signature was invalid", "id": "INVALID_SIGNATURE", "description": "Expired timestamp: given 14809047 (truncated...)
```

Laravel 5.3 on PHP 5.6

```
    public function search(Request $request)
    {
        $client = new Client([
            'consumerKey' => env('YELP_CONSUMER_KEY'),
            'consumerSecret' => env('YELP_CONSUMER_SECRET'),
            'token' => env('YELP_TOKEN'),
            'tokenSecret' => env('YELP_TOKEN_SECRET'),
        ]);

        $client->setSearchLimit(10);

        $results = $client->search(array('term' => 'tacos', 'location' => 'Nashville, TN'));

        return $this->response->json([$results]);
    }
```

Some code to help the debug.

**Comment by matthewtrask** [comment]
Log output: 
```
[2016-12-05 02:45:39] local.ERROR: exception 'Stevenmaguire\Yelp\Exception' with message 'Client error: `GET http://api.yelp.com/v2/search/?term=tacos&location=Nashville&limit=10` resulted in a `400 Bad Request` response:
{"error": {"text": "Signature was invalid", "id": "INVALID_SIGNATURE", "description": "Expired timestamp: given 14809059 (truncated...)
' in /var/www/public/gitlab-demo/vendor/stevenmaguire/yelp-php/src/Client.php:251
Stack trace:
#0 /var/www/public/gitlab-demo/vendor/stevenmaguire/yelp-php/src/Client.php(271): Stevenmaguire\Yelp\Client->request('/v2/search/?ter...')
#1 /var/www/public/gitlab-demo/app/Http/Controllers/Api/YelpController.php(48): Stevenmaguire\Yelp\Client->search(Array)
#2 [internal function]: App\Http\Controllers\Api\YelpController->search(Object(Illuminate\Http\Request))
#3 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#4 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('search', Array)
#5 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(190): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\YelpController), 'search')
#6 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#7 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#30 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 /var/www/public/gitlab-demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#39 /var/www/public/gitlab-demo/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#40 {main}  
```

**Comment by stevenmaguire** [comment]
Are you positive that you have the correct values for all four of the yelp token attributes? Are you certain you have the latest package updates? I doubt this is an issue with this library because I am using another pakcage to handle all the OAuth handling and this is the first issue I've heard of related to this. 

https://www.yelp.com/developers/documentation/v2/errors

I'm not ruling out that fact there may be code changes needed here, I would like to make sure the issues is not caused by your implementation or Yelps service first.

**Comment by matthewtrask** [comment]
Yes, double checked the values too. Even regenerated the tokens on the Yelp API just to test. 

It did work yesterday morning after talked about the other issue, but then reverted back to the 400 INVALID SIGNATURE error.

**Comment by stevenmaguire** [comment]
My guess is that something is not quite right between Yelps service and the data you've provided. I tested this package just now and it seems to be working with the credentials I have provided, which have not been refreshed recently.

**Comment by matthewtrask** [comment]
I will go back and double check the tokens tonight just to see if it is something I may have done.
